### ISSUE TITLE
Figure a way to fetch current drafts / posts from Wordpress

### ISSUE THREAD

**Issue by yuvipanda** [AlexTatiyants/platen#19]
Highly problematic, because WP has them in HTML and we want Markdown. Conversion that way isn't really easy.

**Comment by AlexTatiyants** [comment]
That was exactly the impression I got when I first looked at it. There are a libraries which can do it, but I haven't tested them. We can also write a custom converter, perhaps focusing on just a handful of HTML elements and ignoring the rest. Either way this will not be trivial to implement.

**Comment by yuvipanda** [comment]
I'm of the opinion that we shouldn't really implement this. We can probably save our markdown contents of drafts as a property (metadata) of each post, and sync that - so drafts from platen will sync across, others won't. That, IMO, is an acceptable solution.  We shouldn't really try to parse HTML into Markdown.

**Comment by AlexTatiyants** [comment]
Let's think about this for a moment. This feature would solve two problems:
1. Porting existing content from your blog into Platen so that Platen can be the primary editor.
2. Allowing users to either use Platen on multiple machines or have Platen be one of multiple editors (like editors on mobile devices for example) by essentially using WordPress as a cloud store.

These needs imply pretty different usage patterns (though I have a need for both). Also, issue 1 is more of a one-time setup, while issue 2 is an ongoing thing. 

Your proposal would partially address issue 2, but won't do much for 1. To me, the real question is this: what type of tool are we building here? A "one-and-only" editor or one of many? 

Thoughts?

**Comment by yuvipanda** [comment]
My thinking is that if we do something, we should really, really _nail_ it and do it well. 

That isn't possible for (1), since HTML -> MD conversion is tough, and mostly not even 1:1. And the use cases for that is also minimal - one time only. 

(2) is far more useful, since people can have platen installed in different devices (I bet this can run on tablets nicely with minimal modifications), and it will automatically sync between them. We _can_ nail this since we have control over what we sync to WP. It also is not '1 time' and has much more usage, especially if we make the app kickass enough :) 

So I think we should only do (2), and be a 'one and only' editor. The upshot of Platen for me is the ease of use of writing up new posts and the fact that it is distraction free. Editing older posts / posts from other tools should be left to other tools.

**Comment by AlexTatiyants** [comment]
Points well taken and I completely agree that it should either be awesome or not be there at all. 

That said, I read a recent review of Platen (http://fabledbeggar.wordpress.com/2013/07/19/a-markdown-editor-for-wordpress-3/) in which the author makes the point that he wants to be able to start a post on his Android phone and then actually work on it in Platen. 

Now, I don't know if we necessarily want to support this specific use case. But, if we did, maybe we wouldn't need to solve the hard problem (convert HTML to MD), but just grab the text and dump it sans formatting (with a warning of "formatting will be lost ...").

**Comment by yuvipanda** [comment]
If we grab it, strip formatting, and then sync it back, we're sortof losing data there, aren't we?

I like that the tagline is 'Markdown Wordpress Editor', and think we should keep it that way. The 'Mobile' -> System workflow can be later supported by pushing this on Mobile, I'd think. If we can't make safe, non-messy HTML -> MD conversion, we shouldn't do it.

**Comment by AlexTatiyants** [comment]
Ok, I'll let it go :) Thanks for the engaging discussion!

**Comment by yuvipanda** [comment]
Alright, so to summarize:
1. Platen is going to be a 'Markdown' Wordpress Editor, than a 'does everything' wordpress editor
2. We won't attempt to parse HTML from other blog editors back into markdown, since that is teh suck.
3. Markdown <3

I'll close this as 'WONTFIX', and open a new issue about saving original markdown as meta info in WP.
