### ISSUE TITLE
Correct login parameters for self-hosted WP blog?

### ISSUE THREAD

**Issue by skopp** [AlexTatiyants/platen#26]
I can't seem to connect to my self-hosted Wordpress setup. I don't think there's anything wrong with XML-RPC or anything on it, because I can connect without any issues using the Blackberry OS7.1 WP app.

What could I be doing wrong? Sorry if this was asked before, I didn't see it

**Comment by AlexTatiyants** [comment]
Are there any errors in the log? All you need to do to connect is put in your blog's url (without the XMLRPC suffix) and account info.

**Comment by skopp** [comment]
I just used the address, username and password. shot of log -  http://d.pr/i/YvPn

**Comment by warren5236** [comment]
Try adding http:// to the beginning of the url for your blog.  That caused me problems.

**Comment by skopp** [comment]
Thanks. That worked :+1:
