### ISSUE TITLE
Show 'no posts yet' or something similar in Posts view

### ISSUE THREAD

**Issue by yuvipanda** [AlexTatiyants/platen#4]
When there are no posts. Currently just empty.

**Comment by AlexTatiyants** [comment]
definitely, this is probably the most confusing part of Platen right now.

**Comment by yuvipanda** [comment]
Indeed. Also perhaps a notice about needing to configure your blog on first run?

**Comment by yuvipanda** [comment]
Not sure why the pull request is #5 rather than being attached to this one though. Would be nice if that could be merged :)

**Comment by AlexTatiyants** [comment]
I'm sorry it's taking me a while to get this merged. I'm having weird Sublime Text problems on my machine at the moment. As soon as I sort that out, I'll merge it.

**Comment by yuvipanda** [comment]
Fixed in #5.
